[tool.poetry]
name = "quintet-poker"
version = "0.1.0"
description = "A simple poker game using FastAPI and SQLite"
authors = ["Daniel(Donghyun) Sung <donghyun.main@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.0"
uvicorn = "^0.31.0"
sqlalchemy = "^2.0.35"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
black = "^24.8.0"
flake8 = "^7.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
